baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "blog"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = true

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[permalinks]
  blog = "/:title/"

[taxonomies]
   tag = "tags"

[languages]
  [languages.en]
    title = "Toluwalemi"
    subtitle = "BLOG"
    keywords = "Toluwalemi, Tolu, Toluwalemi Oluwadare, Toluwalemi's Blog"
    copyright = ""
    menuMore = "Show more"
    writtenBy = ""
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    lastModDisplay = "Last Updated:"

    [languages.en.params.logo]
      logoText = "BLOG"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "http://www.toluwalemi.com/about/"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Reading"
        url = "/reading"